/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.rs"
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Default/Slate theme
        slate: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        // Spring theme
        emerald: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        // Summer theme
        amber: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        // Fall theme
        orange: {
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
          950: '#431407',
        },
        // Winter theme
        sky: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        // Halloween theme
        purple: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7e22ce',
          800: '#6b21a8',
          900: '#581c87',
          950: '#3b0764',
        },
      },
    },
  },
  plugins: [],
  // Core plugins are explicitly enabled to prevent unexpected utility classes
  corePlugins: {
    // Layout
    container: true,
    display: true,
    position: true,
    float: false,
    clear: false,
    objectFit: false,
    objectPosition: false,
    overflow: true,
    overscrollBehavior: false,
    visibility: true,
    zIndex: true,

    // Flexbox & Grid
    flexbox: true,
    grid: true,
    gap: true,

    // Spacing
    padding: true,
    margin: true,
    space: true,

    // Sizing
    width: true,
    minWidth: true,
    maxWidth: true,
    height: true,
    minHeight: true,
    maxHeight: true,

    // Typography
    fontFamily: true,
    fontSize: true,
    fontWeight: true,
    letterSpacing: true,
    lineHeight: true,
    textAlign: true,
    textColor: true,
    textDecoration: true,
    textOverflow: true,
    textTransform: false,
    verticalAlign: false,
    whitespace: true,
    wordBreak: false,

    // Backgrounds
    backgroundColor: true,
    backgroundImage: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    gradientColorStops: false,

    // Borders
    borderRadius: true,
    borderWidth: true,
    borderColor: true,
    borderStyle: true,
    divideWidth: false,
    divideColor: false,
    divideStyle: false,
    ringWidth: true,
    ringColor: true,
    ringOffsetWidth: false,
    ringOffsetColor: false,

    // Effects
    boxShadow: true,
    opacity: true,
    transform: false,
    transformOrigin: false,
    scale: true,
    rotate: false,
    translate: false,
    skew: false,

    // Transitions & Animation
    transitionProperty: true,
    transitionDuration: true,
    transitionTimingFunction: true,
    transitionDelay: false,
    animation: false,

    // Interactivity
    cursor: true,
    pointerEvents: true,
    resize: false,
    userSelect: true,
    outline: true,

    // SVG
    fill: false,
    stroke: false,
    strokeWidth: false,
  },
  // Safelist ensures critical utility classes are always included
  safelist: [
    // Theme modes
    'dark',
    'light',
    // Layout
    'container',
    'mx-auto',
    'px-4',
    'py-2',
    'py-4',
    'fixed',
    'top-4',
    'right-4',
    'z-50',
    'flex',
    'flex-col',
    'items-center',
    'justify-between',
    'gap-2',
    'space-x-2',
    'space-x-4',
    'space-y-4',
    // Typography
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    // Colors - Default/Slate
    'text-slate-100',
    'text-slate-400',
    'text-slate-600',
    'text-slate-900',
    'bg-white',
    'bg-slate-50',
    'bg-slate-100',
    'bg-slate-800',
    'bg-slate-900',
    'border-slate-200',
    'border-slate-700',
    'ring-slate-400',
    'ring-slate-500',
    // Colors - Spring/Emerald
    'text-emerald-300',
    'text-emerald-400',
    'text-emerald-600',
    'text-emerald-700',
    'bg-emerald-50',
    'bg-emerald-100',
    'bg-emerald-800',
    'bg-emerald-950',
    'border-emerald-200',
    'border-emerald-700',
    'border-emerald-800',
    'ring-emerald-400',
    'ring-emerald-500',
    // Colors - Summer/Amber
    'text-amber-300',
    'text-amber-400',
    'text-amber-600',
    'text-amber-700',
    'bg-amber-50',
    'bg-amber-100',
    'bg-amber-800',
    'bg-amber-950',
    'border-amber-200',
    'border-amber-700',
    'border-amber-800',
    'ring-amber-400',
    'ring-amber-500',
    // Colors - Fall/Orange
    'text-orange-300',
    'text-orange-400',
    'text-orange-600',
    'text-orange-700',
    'bg-orange-50',
    'bg-orange-100',
    'bg-orange-800',
    'bg-orange-950',
    'border-orange-200',
    'border-orange-700',
    'border-orange-800',
    'ring-orange-400',
    'ring-orange-500',
    // Colors - Winter/Sky
    'text-sky-300',
    'text-sky-400',
    'text-sky-600',
    'text-sky-700',
    'bg-sky-50',
    'bg-sky-100',
    'bg-sky-800',
    'bg-sky-950',
    'border-sky-200',
    'border-sky-700',
    'border-sky-800',
    'ring-sky-400',
    'ring-sky-500',
    // Colors - Halloween/Purple
    'text-purple-300',
    'text-purple-400',
    'text-purple-600',
    'text-purple-700',
    'bg-purple-50',
    'bg-purple-100',
    'bg-purple-800',
    'bg-purple-950',
    'border-purple-200',
    'border-purple-700',
    'border-purple-800',
    'ring-purple-400',
    'ring-purple-500',
    // Interactive states
    'hover:bg-slate-200',
    'hover:bg-emerald-200',
    'hover:bg-amber-200',
    'hover:bg-orange-200',
    'hover:bg-sky-200',
    'hover:bg-purple-200',
    'dark:hover:bg-slate-700',
    'dark:hover:bg-emerald-700',
    'dark:hover:bg-amber-700',
    'dark:hover:bg-orange-700',
    'dark:hover:bg-sky-700',
    'dark:hover:bg-purple-700',
    'hover:scale-105',
    'scale-110',
    'hover:opacity-80',
    'focus:outline-none',
    'focus:ring-2',
    'ring-2',
    'ring-offset-2',
    // Transitions
    'transition-colors',
    'transition-all',
    'duration-200',
    // Add dark mode variants for all color classes
    'dark:bg-slate-950',
    'dark:bg-emerald-950',
    'dark:bg-amber-950',
    'dark:bg-orange-950',
    'dark:bg-sky-950',
    'dark:bg-purple-950',
    // Add hover variants for dark mode
    'dark:hover:bg-slate-800',
    'dark:hover:bg-emerald-800',
    'dark:hover:bg-amber-800',
    'dark:hover:bg-orange-800',
    'dark:hover:bg-sky-800',
    'dark:hover:bg-purple-800',
    // Add ring offset classes
    'ring-offset-white',
    'dark:ring-offset-slate-900',
    'ring-offset-4',
  ],
} 