[build]
target = "index.html"
dist = "dist"
# Run CSS build before the main build
hook = ["yarn build:css"]

[serve]
address = "127.0.0.1"
port = 3000

[watch]
watch = ["src", "assets"]

[[hooks]]
stage = "pre_build"
command = "yarn"
command_arguments = ["build:css"] 